### ISSUE TITLE
Social Media Pinterest Enhancement and Feature.

### ISSUE THREAD

**Issue by georginajuarez** [suwebdev/great-sunrise#15]
**Issue**
Enhancement: User story needs to specify if user is redirected to Pinterest after sharing post via platform API or if they are redirected back to current page. User story should also include some sort of success action/notification once task is completed by user.
Feature: Pinterest API allows for a simultaneous post to Facebook. This feature should be made available to users so that they can post to both in one action instead of two.

**Example of new feature**
<img width="300" alt="pinterest fb share" src="https://user-images.githubusercontent.com/17970611/31874605-00fae59a-b77f-11e7-9a68-98ef5003f1b2.png">

**Considerations**
- Add that user should be directed back to current poem on poetry page.
- User should receive a success notification before being redirected back to poetry page.
- Pinterest users should be able to also share/post to Facebook in the same action.

**Priority**
The **enhancement** addition should be included in the **current sprint** as it is an important feature and should not add much more time to the estimation size.
The **new feature** can wait for the **next sprint** as not including it is not detrimental to it's current function.

**User Story**
As a User, I want to post to Pinterest, so that I can share poetry with my followers.
[Social Media User Story #2](https://github.com/suwebdev/great-sunrise/wiki/Social-Media-User-Stories)

**Current Estimated Size** Md (3-5 days)

**Acceptance criteria:**

- User has the option to share to Pinterest.
- Posts are shared to the correct platform.

**TOTAL TIME TO COMPLETE USER STORY AND ISSUE** 4 days + 1 day for issue

**Comment by millerlara** [comment]
#16 pull request for Issue

**Comment by georginajuarez** [comment]
Pull request #35 created to address this issue.
